kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k0s-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31
    extraPortMappings:
#      - containerPort: 8080
#        hostPort: 8080
#        listenAddress: "0.0.0.0"
#      - containerPort: 8443
#        hostPort: 8443
#        listenAddress: "0.0.0.0"

      - containerPort: 30000
        hostPort: 30000
        listenAddress: "0.0.0.0"
      - containerPort: 30001
        hostPort: 30001
        listenAddress: "0.0.0.0"
      - containerPort: 30002
        hostPort: 30002
        listenAddress: "0.0.0.0"

      - containerPort: 30003
        hostPort: 30003
        listenAddress: "0.0.0.0"
      - containerPort: 30004
        hostPort: 30004
        listenAddress: "0.0.0.0"
      - containerPort: 30005
        hostPort: 30005
        listenAddress: "0.0.0.0"
      - containerPort: 30006
        hostPort: 30006
        listenAddress: "0.0.0.0"
      - containerPort: 30007
        hostPort: 30007
        listenAddress: "0.0.0.0"
      - containerPort: 30008
        hostPort: 30008
        listenAddress: "0.0.0.0"
      - containerPort: 30009
        hostPort: 30009
        listenAddress: "0.0.0.0"
      - containerPort: 30010
        hostPort: 30010
        listenAddress: "0.0.0.0"
      - containerPort: 30011
        hostPort: 30011
        listenAddress: "0.0.0.0"
