apiVersion: configuration.github.com/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: app-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: app-controller
  name: b
spec:
  image: nginx:latest
  replicas: 2
  enable_ingress: true
  enable_service: true
